../../rtl/opcode.sv
../../rtl/funct3.sv
../../rtl/funct7.sv
../../rtl/riscv.sv
../../rtl/alu.sv
../../rtl/axis.sv
../../rtl/core.sv
../../rtl/execute.sv
../../rtl/fetch.sv
../../rtl/regfile.sv
../../rtl/rs232.sv
