TOP = top
PKG = $(RTLDIR)/riscv.sv
SRC = $(RTLDIR)/alu.sv     \
      $(RTLDIR)/control.sv \
      $(RTLDIR)/core.sv    \
      $(RTLDIR)/memory.sv  \
      $(RTLDIR)/ram.sv     \
      $(RTLDIR)/regfile.sv

include ../vivado.mk
