#
# Copyright 2015, 2016 C. Brett Witherspoon
#
# See LICENSE for more details.
#

TOP = testbench.sv
PKG = axi4.sv    \
      core.sv
INT = axi.sv
RTL = alu.sv     \
      bram.sv    \
      control.sv \
      cpu.sv    \
      fetch.sv   \
      memory.sv  \
      ram.sv     \
      regfile.sv

include ../vivado.mk
